import Link from "next/link";

const steps = [
  ["1", "Listens", "Keeps up with the room using live captions."],
  ["2", "Predicts in your voice", "Prepares replies that sound like you, while people are still talking."],
  ["3", "Tap one or steer", "Choose a ready thought, change the tone, or add a keyword."],
  ["4", "Speaks in your voice", "Says what you mean at the moment it matters."],
];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-[#f7faf7] text-[#12322e] dark:bg-[#0d211e] dark:text-[#f4fbf6]">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><Link href="/" className="flex items-center gap-3 rounded-xl font-bold focus:outline-none focus:ring-4 focus:ring-[#9fdfbd]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#173d3a] text-lg text-white">C</span><span className="text-xl tracking-tight">Cadence</span></Link><Link href="/app" className="min-h-11 rounded-xl px-4 py-2 text-sm font-bold text-[#1b6d4e] hover:bg-[#e6f3eb] focus:outline-none focus:ring-4 focus:ring-[#9fdfbd] dark:text-[#a8e5c2] dark:hover:bg-[#173d3a]">Open demo</Link></header>
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-12 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:pb-28 lg:pt-20"><div><p className="eyebrow">Conversation, on your terms</p><h1 className="mt-4 max-w-3xl text-5xl font-bold tracking-[-0.045em] sm:text-6xl lg:text-7xl">Be in the conversation again.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#4f6d64] dark:text-[#c3d9cf]">Cadence listens ahead and stages the words you would want to say, so joining a fast conversation can take one tap instead of a minute of typing.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/app" className="min-h-14 rounded-2xl bg-[#1f7a57] px-6 py-4 text-base font-bold text-white shadow-lg shadow-[#1f7a57]/20 transition hover:bg-[#166343] focus:outline-none focus:ring-4 focus:ring-[#9fdfbd]">Try the live demo</Link><a href="#how-it-works" className="min-h-14 rounded-2xl border border-[#b8d1c2] px-6 py-4 text-base font-bold text-[#234b3e] hover:bg-white focus:outline-none focus:ring-4 focus:ring-[#9fdfbd] dark:border-[#58776d] dark:text-[#d9eee3] dark:hover:bg-[#173d3a]">See how it works</a></div></div><div className="rounded-[2rem] border border-[#d4e4da] bg-[#eaf6ef] p-5 shadow-card dark:border-[#31564c] dark:bg-[#173d3a]"><div className="rounded-3xl bg-white p-5 dark:bg-[#102a26]"><p className="eyebrow">Ready to say</p><p className="mt-3 text-xl font-bold leading-relaxed">“I love that idea, kiddo. A little fresh air sounds like the right playlist.”</p><div className="mt-5 flex items-center justify-between border-t border-[#e5eee8] pt-4 text-sm font-bold text-[#1d6a4b] dark:border-[#31564c] dark:text-[#a8e5c2]"><span>One tap to speak</span><span aria-hidden="true">Ready</span></div></div><p className="px-3 pb-1 pt-5 text-sm font-semibold text-[#53756a] dark:text-[#c3d9cf]">The room moves fast. Your voice should not have to wait.</p></div></section>
      <section className="px-5 pb-2 sm:px-8"><p className="mx-auto max-w-6xl rounded-2xl border border-[#b9ddc8] bg-[#eaf8ef] px-5 py-4 text-center text-lg font-bold leading-relaxed text-[#205342] dark:border-[#467566] dark:bg-[#173d3a] dark:text-[#d9eee3]">No training for anyone else. They just talk - Cadence listens and gets your words ready.</p></section>
      <section className="border-y border-[#dce9e1] bg-white py-18 dark:border-[#31564c] dark:bg-[#102a26]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="eyebrow">The problem</p><div className="mt-4 grid gap-8 md:grid-cols-[.9fr_1.1fr]"><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">A conversation does not wait for a keyboard.</h2><p className="text-lg leading-relaxed text-[#4f6d64] dark:text-[#c3d9cf]">Typical conversation moves at <strong className="text-[#173d3a] dark:text-white">100–140 words per minute.</strong> Many AAC users communicate at <strong className="text-[#173d3a] dark:text-white">3–20 words per minute.</strong> The gap is not just speed. It is timing, personality, and presence.</p></div></div></section>
      <section id="how-it-works" className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><p className="eyebrow">How it works</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">A faster path from thought to voice.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, description]) => <article key={number} className="rounded-3xl border border-[#d7e5dc] bg-white p-6 shadow-sm dark:border-[#31564c] dark:bg-[#173d3a]"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e3f4eb] text-sm font-black text-[#1f7a57] dark:bg-[#244b41] dark:text-[#a8e5c2]">{number}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-[#56736a] dark:text-[#c3d9cf]">{description}</p></article>)}</div></section>
      <section className="bg-[#173d3a] px-5 py-20 text-white sm:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b9d5c6]">Why it&apos;s different</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Presence, not just faster typing.</h2></div><p className="text-lg leading-relaxed text-[#d6e6dd]">Cadence is built for the small, human moments that can slip away: the joke, the gentle disagreement, the loving aside. It helps people with ALS stay in the rhythm of the room in their own voice.</p></div></section>
      <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><div className="rounded-[2rem] bg-[#fff1df] p-8 sm:p-12"><p className="eyebrow text-[#8b572f]">Who it&apos;s for</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">For people with ALS who want more than a way to type.</h2><p className="mt-4 max-w-2xl text-lg leading-relaxed text-[#73583f]">For the people who want to share the story, land the punchline, and be heard while the moment is still theirs.</p><Link href="/app" className="mt-7 inline-flex min-h-14 items-center rounded-2xl bg-[#1f7a57] px-6 py-4 font-bold text-white focus:outline-none focus:ring-4 focus:ring-[#9fdfbd]">Try the live demo</Link></div></section>
      <footer className="border-t border-[#dce9e1] px-5 py-8 text-center text-sm font-medium text-[#5d796f] dark:border-[#31564c] dark:text-[#c3d9cf]">Cadence — every voice deserves its moment.</footer>
    </main>
  );
}
